version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  
  pre_build:
    commands:
      - echo "Build started on $(date)"
  
  build:
    commands:
      - echo "Zipping flink_app directory..."
      - cd flink_app
      - zip -r ../flink_app.zip .
      - cd ..
      
      - echo "Uploading zipped artifact to S3..."
      - aws s3 cp flink_app.zip s3://nitish-wiki-monitor-code/flink_app.zip
      
      - echo "Syncing other code (producer, infra) to S3..."
      - aws s3 sync producer/ s3://nitish-wiki-monitor-code/producer/ --delete
      - aws s3 sync infra/ s3://nitish-wiki-monitor-code/infra/ --delete
  
  post_build:
    commands:
      - echo "Build completed."
      - echo "Artifact at s3://nitish-wiki-monitor-code/flink_app.zip"